### ISSUE TITLE
Feature Request/Question: Public Facing AH Prices API

### ISSUE THREAD

**Issue by JWilliamsGH** [EdenServer/eden-web#204] opened 2022-05-05 22:22 UTC
Is there a public facing API for the auction house prices? I was interested in building a crafting tool that utilizes this information. Tinkering with prices in excel is functional but tedious.

**Comment by ejedev** [comment] 2022-05-07 21:40
The API that the frontend uses to fetch prices is publically accesible, you can check out the various endpoints [here.](https://github.com/EdenServer/eden-web/tree/develop/api/v1). There isn't any official documentation that I'm aware of so probably try to avoid sending too many requests.

For example, to get the recent sales of a stack of gold ingots you can send a GET request to `https://edenxi.com/api/v1/items/gold_ingot/ah?stack=true`.

The response would look something like this:

```
[{"name":"gold_ingot","seller_name":"Atryx","buyer_name":"Pawpaw","sale":90000,"sell_date":1651926955},{"name":"gold_ingot","seller_name":"Selina","buyer_name":"Pawpaw","sale":90000,"sell_date":1651926947},{"name":"gold_ingot","seller_name":"Selina","buyer_name":"Apessius","sale":90000,"sell_date":1651896094},{"name":"gold_ingot","seller_name":"Selina","buyer_name":"Steam","sale":90000,"sell_date":1651861753},{"name":"gold_ingot","seller_name":"Selina","buyer_name":"Steam","sale":90000,"sell_date":1651861747},{"name":"gold_ingot","seller_name":"Selina","buyer_name":"Pawpaw","sale":90000,"sell_date":1651849411},{"name":"gold_ingot","seller_name":"Selina","buyer_name":"Bokbok","sale":90000,"sell_date":1651817515},{"name":"gold_ingot","seller_name":"Selina","buyer_name":"Thranduil","sale":89999,"sell_date":1651772819},{"name":"gold_ingot","seller_name":"Kwi","buyer_name":"Thranduil","sale":89000,"sell_date":1651772779},{"name":"gold_ingot","seller_name":"Selina","buyer_name":"Radagast","sale":90000,"sell_date":1651695102}]
```

**Comment by slassen** [comment] 2023-08-06 22:41
Closing as the issue is already solved

**Closed as completed by slassen** 2023-08-06 22:41 UTC
